public enum EventList
{
    DISPLAY_TEXT,
    HIDE_COMBAT_UI,
    SHOW_COMBAT_UI,
    ACTIVATE_COMBAT_LOG,
    DISPLAY_SKILLSET_EDITOR,
    FIGHTER_STUFF_UPDATE,
    TEAM_MEMBER_UI_SELECT,
    SHOW_PARTS_LIST,
    HIDE_PARTS_LIST
}

public enum PartType
{
    ARM,
    SHOULDER
}

public enum PartSlot
{
    LEFT_ARM,
    RIGHT_ARM,
    LEFT_SHOULDER,
    RIGHT_SHOULDER
}